global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'lambda-metrics'
    static_configs:
      - targets: ['${metrics_api_url}'] # API Gateway URL for metrics service
    metrics_path: '/dev/metrics'
    scrape_interval: 30s
    scheme: 'https'
